export const USERS_REQUEST = 'USERS_REQUEST';

export const USERS_REQUEST_SUCCESS = 'USERS_REQUEST_SUCCESS';

export const USERS_REQUEST_FAILURE = 'USERS_REQUEST_FAILURE';

export const ACTIVE_USER = 'ACTIVE_USER';

export const FIND_SMTH_SUCCESS = 'FIND_SMTH_SUCCESS';

export const FIND_SMTH_FAILURE = 'FIND_SMTH_FAILURE';